spring:
  application:
    name: catalogo
  mongodb:
    uri: mongodb://localhost:27017/catalogo
  data:
    mongodb:
      auto-index-creation: true
      representation:
        big-decimal: decimal128

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always